Automaton:
	g++ -c Automaton.cpp
PatternSearch:
	g++ -c PatternSearch.cpp
FileParser:
	g++ -c FileParser.cpp
main:
	g++ -o main main.cpp Automaton.o PatternSearch.o FileParser.o
all:
	make Automaton
	make PatternSearch
	make FileParser
	make main
clean:
	rm main
	rm *.o

